### ISSUE TITLE
图片太多/太大时 OutOfMemoryError

### ISSUE THREAD

**Issue by mzlogin** [mzlogin/guanggoo-android#1]
页面：<http://www.guanggoo.com/t/25527#reply1>

报错：

```
09-17 22:51:29.037 24165-24718/org.mazhuang.guanggoo E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #3
   Process: org.mazhuang.guanggoo, PID: 24165
   java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:318)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
    Caused by: java.lang.OutOfMemoryError: Failed to allocate a 34813404 byte allocation with 16772752 free bytes and 29MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
       at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
       at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:650)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:626)
       at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:664)
       at android.graphics.drawable.BitmapDrawable.<init>(BitmapDrawable.java:192)
       at org.mazhuang.guanggoo.util.MyHttpImageGetter$ImageGetterAsyncTask.fetchDrawable(MyHttpImageGetter.java:115)
       at org.mazhuang.guanggoo.util.MyHttpImageGetter$ImageGetterAsyncTask.doInBackground(MyHttpImageGetter.java:78)
       at org.mazhuang.guanggoo.util.MyHttpImageGetter$ImageGetterAsyncTask.doInBackground(MyHttpImageGetter.java:56)
       at android.os.AsyncTask$2.call(AsyncTask.java:304)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
       at java.lang.Thread.run(Thread.java:761) 
```

与 <https://github.com/PrivacyApps/html-textview/issues/106> 一样。

**Comment by mzlogin** [comment]
目前展示主题详情时使用 WebView 替代了 html-textview，暂时没有这个问题了。
